language: php

sudo: required

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 8.3

env:
  - MOODLE_BRANCH=MOODLE_51_STABLE DB=pgsql
  - MOODLE_BRANCH=master DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 16
  - nvm use 16
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
